import { render, screen } from "@testing-library/react"
import React from "react"

import RootLayout, { metadata } from "../app/layout"

describe("RootLayout", () => {
  it("renders children inside the html shell", () => {
    render(
      <RootLayout>
        <p>Child content</p>
      </RootLayout>,
    )

    expect(document.querySelector("html")).toHaveAttribute("lang", "en")
    expect(screen.getByText("Child content")).toBeInTheDocument()
  })
})

describe("layout metadata", () => {
  it("exposes the default page title and description", () => {
    expect(metadata.title).toBe("Create Next App")
    expect(metadata.description).toContain("Generated by create next app")
  })
})
